import path from "path";

export function join(...paths: string[]): string {
    return path.join(process.cwd(), "examples", "mocha", ...paths);
}

export function minify(code: string): string {
    return code.replace(/\s*\n\s*/g, "");
}

export function enforceComment(code: string): string {
    return `/* Generated by: scripts/mocha */\n\n${code}`;
}
